name: Labeler

on:
  push:
    branches:
      - main

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      issues: write # <--- permission granted explicitely
      security-events: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v5.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-delete: true
